version: '3.2'

services: 
    egat-p2p-webadmin:
        build: . 
        image: egat-p2p-webadmin:0.0.1
        volumes:
          - '.:/usr/src/app'
          - '/usr/src/app/node_modules'
        ports:
          - 3004:3004
        networks:
          - basic
        stdin_open: true  

networks:
  basic:

#     keycloak:
#         image: jboss/keycloak
#         environment: 
#             DB_VENDOR: POSTGRES
#             DB_ADDR: postgres
#             DB_DATABASE: keycloak
#             DB_USER: keycloak
#             DB_SCHEMA: public
#             DB_PASSWORD: password
#             KEYCLOAK_USER: admin
#             KEYCLOAK_PASSWORD: admin
#         ports: 
#             - 8080:8080
#         depends_on:
#             - postgres

#     postgres:
#         image: postgres
#         volumes:
#             - postgres_data:/var/lib/postgresql/data
#         environment:
#             POSTGRES_DB: keycloak
#             POSTGRES_USER: keycloak
#             POSTGRES_PASSWORD: password

# volumes: 
#     postgres_data:
#         driver: local
